contact_links:
  - name: FAQ's
    url: https://github.com/doubleangels/NextDNSManager/blob/main/README.md#faq
    about: Please read the FAQ's before creating an issue or your issue may be closed.
blank_issues_enabled: false